# Generated by Django 3.1 on 2020-08-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eventos',
            fields=[
                ('id_evento', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre_evento', models.CharField(max_length=40)),
                ('fecha_evento', models.DateField()),
            ],
        ),
    ]
