# Generated by Django 3.1 on 2020-08-27 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20200826_2057'),
    ]

    operations = [
        migrations.CreateModel(
            name='empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=40)),
                ('cod_postal', models.CharField(max_length=6)),
                ('mail_inscripciones', models.EmailField(max_length=254)),
                ('mail_rrhh', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='certificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evento',
            name='costo_inscripcion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evento',
            name='desc_seguridad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='evento',
            name='empresa_organizadora',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventos.empresa'),
        ),
    ]
