# Generated by Django 3.1 on 2020-08-27 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20200826_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='empresa_organizadora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.empresa'),
        ),
    ]
