# Generated by Django 3.1 on 2020-09-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20200826_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='categoria_evento',
            field=models.CharField(default='Maraton', max_length=40),
            preserve_default=False,
        ),
    ]
