# Generated by Django 3.1 on 2020-09-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20200907_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fotoevento',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_eventos'),
        ),
    ]
