# Generated by Django 3.1 on 2020-09-07 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0008_auto_20200907_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_eventos'),
        ),
    ]
