# Generated by Django 3.1 on 2020-09-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_evento_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='logo',
            field=models.ImageField(blank=True, default='No_Image_Profile.png', null=True, upload_to='fotos_eventos'),
        ),
    ]
