# Generated by Django 3.1 on 2020-09-26 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0011_auto_20200926_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='evento',
            name='categoria_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.categoriaevento'),
        ),
    ]
