# Generated by Django 3.1 on 2020-09-26 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0012_auto_20200926_1119'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoEvento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=40)),
            ],
        ),
        migrations.AddField(
            model_name='evento',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='eventos.estadoevento'),
        ),
    ]
