# Generated by Django 3.1 on 2020-09-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comun',
            name='apellido',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comun',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='comun',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='comun',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
