# Generated by Django 3.1 on 2020-09-05 15:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_auto_20200905_1220'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comun',
            new_name='Usuario_Comun',
        ),
    ]
