# Generated by Django 3.1 on 2020-09-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200905_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario_comun',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
