# Generated by Django 3.1 on 2020-09-06 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200906_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comun',
            name='profile_pic',
            field=models.ImageField(blank=True, default='No_Image_Profile.png', null=True, upload_to=''),
        ),
    ]
