# Generated by Django 3.1 on 2020-09-07 12:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200906_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='comun',
            name='biografia',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
