# Generated by Django 3.1 on 2020-09-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0002_auto_20200905_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_entrenamiento',
            name='dia',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
