# Generated by Django 3.1 on 2020-09-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0003_detalle_entrenamiento_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='categoria_entrenamiento',
            field=models.CharField(default='Maratón', max_length=40),
            preserve_default=False,
        ),
    ]
