# Generated by Django 3.1 on 2020-09-07 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0007_runningteam_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='runningteam',
            old_name='profile_pic',
            new_name='logo',
        ),
    ]
