# Generated by Django 3.1 on 2020-09-08 00:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0008_auto_20200907_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='tipoentrenamiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_tipo', models.CharField(max_length=40)),
                ('descripcion_tipo', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='entrenamiento',
            name='duracion_entrenamiento',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='runningteam',
            name='logo',
            field=models.ImageField(blank=True, default='No_Image_Profile.png', null=True, upload_to='fotos_runningteams'),
        ),
        migrations.AddField(
            model_name='entrenamiento',
            name='tipo_entrenamiento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.tipoentrenamiento'),
            preserve_default=False,
        ),
    ]
