# Generated by Django 3.1 on 2020-09-08 00:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0011_entrenamiento_tipo_entrenamiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrenamiento',
            name='tiempo',
            field=models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(10)]),
            preserve_default=False,
        ),
    ]
