# Generated by Django 3.1 on 2020-09-08 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0012_entrenamiento_tiempo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrenamiento',
            old_name='tiempo',
            new_name='tiempo_estimado',
        ),
    ]
