# Generated by Django 3.1 on 2020-09-08 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entrenamientos', '0014_pedidoentrenador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoentrenador',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
