# Generated by Django 3.1 on 2020-09-08 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0018_entrenamiento_tipo_entrenamiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrenamiento',
            name='tipo_entrenamiento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.tipoentrenamiento'),
        ),
    ]
