# Generated by Django 3.1 on 2020-09-25 17:20

from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0022_auto_20200920_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='runningteam_youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
                ('runningteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entrenamientos.runningteam')),
            ],
        ),
    ]
