# Generated by Django 3.1 on 2020-09-26 22:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamientos', '0025_auto_20200925_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_entrenamiento',
            name='minutos_de_entrenamiento_por_dia',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='categoria_entrenamiento',
        ),
        migrations.RemoveField(
            model_name='entrenamiento',
            name='duracion_entrenamiento',
        ),
        migrations.AlterField(
            model_name='detalle_entrenamiento',
            name='detalle',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
