# Generated by Django 3.1 on 2020-09-27 22:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('foro', '0003_auto_20200920_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(related_name='foro_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
