# Generated by Django 3.1 on 2020-09-27 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0006_comentario_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='liked',
        ),
    ]
