# Generated by Django 3.1 on 2020-10-10 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0008_denuncia'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='baneado',
            field=models.BooleanField(default=False),
        ),
    ]
