# Generated by Django 3.1 on 2020-10-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0009_post_baneado'),
    ]

    operations = [
        migrations.AddField(
            model_name='denuncia',
            name='descartada',
            field=models.BooleanField(default=False),
        ),
    ]
